/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedContactRouteImport } from './routes/_authenticated/contact'
import { Route as AuthenticatedInformationsRouteImport } from './routes/_authenticated/informations'
import { Route as AuthenticatedMedicamentsRouteImport } from './routes/_authenticated/medicaments'
import { Route as AuthenticatedMontreRouteImport } from './routes/_authenticated/montre'
import { Route as AuthenticatedProfilRouteImport } from './routes/_authenticated/profil'
import { Route as AuthenticatedRendezVousRouteImport } from './routes/_authenticated/rendez-vous'
import { Route as AuthenticatedResultatsRouteImport } from './routes/_authenticated/resultats'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedContactRoute = AuthenticatedContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInformationsRoute =
  AuthenticatedInformationsRouteImport.update({
    id: '/informations',
    path: '/informations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMedicamentsRoute =
  AuthenticatedMedicamentsRouteImport.update({
    id: '/medicaments',
    path: '/medicaments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMontreRoute = AuthenticatedMontreRouteImport.update({
  id: '/montre',
  path: '/montre',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfilRoute = AuthenticatedProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRendezVousRoute = AuthenticatedRendezVousRouteImport.update({
  id: '/rendez-vous',
  path: '/rendez-vous',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResultatsRoute = AuthenticatedResultatsRouteImport.update({
  id: '/resultats',
  path: '/resultats',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contact': typeof AuthenticatedContactRoute
  '/informations': typeof AuthenticatedInformationsRoute
  '/medicaments': typeof AuthenticatedMedicamentsRoute
  '/montre': typeof AuthenticatedMontreRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/rendez-vous': typeof AuthenticatedRendezVousRoute
  '/resultats': typeof AuthenticatedResultatsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contact': typeof AuthenticatedContactRoute
  '/informations': typeof AuthenticatedInformationsRoute
  '/medicaments': typeof AuthenticatedMedicamentsRoute
  '/montre': typeof AuthenticatedMontreRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/rendez-vous': typeof AuthenticatedRendezVousRoute
  '/resultats': typeof AuthenticatedResultatsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/contact': typeof AuthenticatedContactRoute
  '/_authenticated/informations': typeof AuthenticatedInformationsRoute
  '/_authenticated/medicaments': typeof AuthenticatedMedicamentsRoute
  '/_authenticated/montre': typeof AuthenticatedMontreRoute
  '/_authenticated/profil': typeof AuthenticatedProfilRoute
  '/_authenticated/rendez-vous': typeof AuthenticatedRendezVousRoute
  '/_authenticated/resultats': typeof AuthenticatedResultatsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/contact'
    | '/informations'
    | '/medicaments'
    | '/montre'
    | '/profil'
    | '/rendez-vous'
    | '/resultats'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/contact'
    | '/informations'
    | '/medicaments'
    | '/montre'
    | '/profil'
    | '/rendez-vous'
    | '/resultats'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/contact'
    | '/_authenticated/informations'
    | '/_authenticated/medicaments'
    | '/_authenticated/montre'
    | '/_authenticated/profil'
    | '/_authenticated/rendez-vous'
    | '/_authenticated/resultats'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/contact': {
      id: '/_authenticated/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof AuthenticatedContactRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/informations': {
      id: '/_authenticated/informations'
      path: '/informations'
      fullPath: '/informations'
      preLoaderRoute: typeof AuthenticatedInformationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/medicaments': {
      id: '/_authenticated/medicaments'
      path: '/medicaments'
      fullPath: '/medicaments'
      preLoaderRoute: typeof AuthenticatedMedicamentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/montre': {
      id: '/_authenticated/montre'
      path: '/montre'
      fullPath: '/montre'
      preLoaderRoute: typeof AuthenticatedMontreRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profil': {
      id: '/_authenticated/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof AuthenticatedProfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rendez-vous': {
      id: '/_authenticated/rendez-vous'
      path: '/rendez-vous'
      fullPath: '/rendez-vous'
      preLoaderRoute: typeof AuthenticatedRendezVousRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/resultats': {
      id: '/_authenticated/resultats'
      path: '/resultats'
      fullPath: '/resultats'
      preLoaderRoute: typeof AuthenticatedResultatsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedContactRoute: typeof AuthenticatedContactRoute
  AuthenticatedInformationsRoute: typeof AuthenticatedInformationsRoute
  AuthenticatedMedicamentsRoute: typeof AuthenticatedMedicamentsRoute
  AuthenticatedMontreRoute: typeof AuthenticatedMontreRoute
  AuthenticatedProfilRoute: typeof AuthenticatedProfilRoute
  AuthenticatedRendezVousRoute: typeof AuthenticatedRendezVousRoute
  AuthenticatedResultatsRoute: typeof AuthenticatedResultatsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedContactRoute: AuthenticatedContactRoute,
  AuthenticatedInformationsRoute: AuthenticatedInformationsRoute,
  AuthenticatedMedicamentsRoute: AuthenticatedMedicamentsRoute,
  AuthenticatedMontreRoute: AuthenticatedMontreRoute,
  AuthenticatedProfilRoute: AuthenticatedProfilRoute,
  AuthenticatedRendezVousRoute: AuthenticatedRendezVousRoute,
  AuthenticatedResultatsRoute: AuthenticatedResultatsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
